name: Documentation

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    runs-on: windows-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Install Sandcastle Help File Builder
        run: choco install sandcastle-help-file-builder -y

      - name: Build Documentation
        run: msbuild "EP Finder Help/EP Finder Help.shfbproj" /p:Configuration=Release

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "EP Finder Help/Help"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4