name: Help

on:
  workflow_run:
    workflows: [ "Test" ]
    types: [ completed ]
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  help:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore EP Finder
        run: dotnet restore "EP Finder/EP Finder.csproj"

      - name: Build EP Finder
        run: dotnet build "EP Finder/EP Finder.csproj" --no-restore --configuration Release

      - name: Restore EP Finder Help
        run: msbuild "EP Finder Help/EP Finder Help.shfbproj" /t:restore

      - name: Build EP Finder Help
        run: msbuild "EP Finder Help/EP Finder Help.shfbproj" /p:Configuration=Release

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "EP Finder Help/Help"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4